### ISSUE TITLE
Problems initializing project on new system

### ISSUE THREAD

**Issue by ciearius** [GeneralMine/S2QUAT#64]
For some wild reason I am not able to get it up and running on my machine. I copied your `.env`, started it once with `docker-compose up` to get all the dependencies and still it has problems finding some files. As a bonus the database seems unwilling to open a port. Even if the port is specified as is and not an environment variable.

Will try again later today.

**Comment by ciearius** [comment]
Is there anything I might've forgotten, while setting this up?

**Comment by GeneralMine** [comment]
Hmmm thats weird. I did the following to get it work:
1. Clone repo
2. Unzip db.zip into ./db
3. Create ./.env like the template
4. Full docker-compose: `docker-compose up --build --remove-orphans`
5. After it's working completely shut it down again
6. Now start the db manually using the docker desktop Application by expanding the s2quat stack -> click run on db
7. Now install all deps for the project: `npm i`
8. Prisma setup: `npx prisma generate`
9. `npm run dev`

I guess you missed the prisma generate step, because that step generates files in the node_modules folder, which is not uploaded.

The problem regarding opening the db port seems like another container is using that one already or because the container is old (the arguments --build and --remove-orphans should fix this).
The Docker Desktop is pretty fancy for debugging their

**Comment by GeneralMine** [comment]
Issue resolved
